### ISSUE TITLE
Naming of Congolese countries

### ISSUE THREAD

**Issue by GeoFDFA** [geometalab/osmaxx#898] opened 2019-02-15 16:09 UTC
The choice available in the country list for the 2 countries of the Congo could be improved upon.
Either the full name could be used or the ISO A3 codes added in brackets perhaps. 
Congo-Kinshasa = Republic of the Congo 
Congo-Brazzaville = Democratic Republic of the Congo
https://en.wikipedia.org/wiki/Congo

**Comment by das-g** [comment] 2019-03-21 13:27
Hi @GeoFDFA 

I finally got around to look into this. Sorry for the long wait.

> Congo-Kinshasa = Republic of the Congo
> Congo-Brazzaville = Democratic Republic of the Congo

Isn't it the other way around (i.e. Congo-Kinshasa = DRC)?

I've renamed the countries as follows:

Congo-Kinshasa &rarr; Congo, Democratic Republic of the (a.k.a. DRC, DROC, Congo-Kinshasa)
Congo-Brazzaville &rarr; Congo, Republic of the (a.k.a. Congo-Brazzaville, Congo Republic, the Congo)

![image](https://user-images.githubusercontent.com/97746/54754911-f796e980-4be4-11e9-9e92-f78623d834c4.png)

This isn't reflected in this Git repo, as the administrative areas are now maintained only in the database, together with the user-created excerpts. (Note to co-maintainers and self: The change was done through the Django admin interface. Public country excerpts previously didn't have an owner, but I had to set the owner of the edited excerpts to something, so the admin interface would let me save them. Thus I've used the lab's account as the new owner.)

Closing. Please re-open if you feel the issue isn't resolved.

**Closed by das-g** 2019-03-21 13:27 UTC

**Comment by GeoFDFA** [comment] 2019-04-02 14:49
Sorry, you are correct re the names, sorry for the confusion.
many thanks for updating the choice!

**Comment by bermufine** [comment] 2020-02-03 14:08
Hi all
But can you put all working m3u8 for congo Kinshasa ?

Please email at congomonpays243@gmail.com
